services:
    bookstack:
        image: ghcr.io/linuxserver/bookstack:latest
        container_name: bookstack
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - APP_URL=http://192.168.1.2:8002
            - DB_HOST=bookstack-db
            - DB_USER=${MYSQL_USER}
            - DB_PASS=${MYSQL_PASSWORD}
            - DB_DATABASE=${MYSQL_DATABASE}
        volumes:
            - ./config:/config
        ports:
            - 8002:80
        restart: unless-stopped
        depends_on:
            - bookstack-db

    bookstack-db:
        image: ghcr.io/linuxserver/mariadb:latest
        container_name: bookstack-db
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./db:/config
        restart: unless-stopped