services:
    bookstack:
        image: lscr.io/linuxserver/bookstack:latest
        container_name: bookstack
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - APP_URL=http://192.168.1.2:8002
            - DB_HOST=bookstack-db
            - DB_USER=${BOOKSTACK_MYSQL_USER}
            - DB_PASS=${BOOKSTACK_MYSQL_PASSWORD}
            - DB_DATABASE=${BOOKSTACK_MYSQL_DATABASE}
        volumes:
            - ${PATH_SERVICES}/bookstack/config:/config
        ports:
            - 8002:80
        restart: unless-stopped
        depends_on:
            - bookstack-db

    bookstack-db:
        image: lscr.io/linuxserver/mariadb:latest
        container_name: bookstack-db
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - MYSQL_ROOT_PASSWORD=${BOOKSTACK_MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${BOOKSTACK_MYSQL_DATABASE}
            - MYSQL_USER=${BOOKSTACK_MYSQL_USER}
            - MYSQL_PASSWORD=${BOOKSTACK_MYSQL_PASSWORD}
        volumes:
            - ${PATH_SERVICES}/bookstack/db:/config
        restart: unless-stopped