services:
    paperless-ng:
        image: lscr.io/linuxserver/paperless-ng:latest
        container_name: paperless-ng
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - PAPERLESS_TIME_ZONE=${TZ}
            - PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{correspondent}-{title}-{created_year}{created_month}{created_day}
            - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
            #- PAPERLESS_ALLOWED_HOSTS=${PAPERLESS_URL}
            #- PAPERLESS_AUTO_LOGIN_USERNAME=${PAPERLESS_USERNAME}
        volumes:
            - ${PATH_SERVICES}/paperless-ng/config:/config
            - ${PATH_SERVICES}/paperless-ng/data:/data
            - ${PATH_SERVICES}/paperless-ng/backups:/backups
        ports:
            - 8004:8000
        restart: unless-stopped