networks:
    proxy-services-net:
        name: proxy-services-net

services:
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        environment:
            - TZ=${TZ}
            - SIGNUPS_ALLOWED=false
            - WEBSOCKET_ENABLED=true
            - LOG_FILE=/data/logs/vaultwarden.log
            - LOG_LEVEL=warn
            - EXTENDED_LOGGING=true
            - ROCKET_CLI_COLORS=off
        volumes:
            - ./config:/data
        networks:
            - proxy-services-net
        restart: unless-stopped

    vaultwarden_backup:
        image: jmqm/vaultwarden_backup:latest
        container_name: vaultwarden_backup
        environment:
            - DELETE_AFTER=30
            - CRON_TIME=* */24 * * * # Runs at 12:00 AM.
            - UID=${PUID}
            - GID=${PGID}
        volumes:
            - ./config:/data:ro # Read-only
            - ./backups:/backups
            - /etc/localtime:/etc/localtime:ro # Container uses date from host.