networks:
    proxy-services-net: 
        name: proxy-services-net

services:
    swag:
        image: lscr.io/linuxserver/swag:latest
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - URL=${SWAG_URL}
            - SUBDOMAINS=wildcard
            - VALIDATION=dns
            - DNSPLUGIN=cloudflare
            - EMAIL=${SWAG_EMAIL}
            - MAXMINDDB_LICENSE_KEY=${MAXMINDDB_LICENSE_KEY}
            - DOCKER_MODS=linuxserver/mods:swag-maxmind|linuxserver/mods:swag-dashboard|linuxserver/mods:swag-crowdsec
            - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
            - CROWDSEC_LAPI_URL=http://crowdsec:8080
            - CROWDSEC_SITE_KEY=${CROWDSEC_SITE_KEY}
            - CROWDSEC_SECRET_KEY=${CROWDSEC_SECRET_KEY}
            - CROWDSEC_F2B_DISABLE=true
        volumes:
            - ${PATH_SERVICES}/proxy-services/swag:/config
        ports:
            - 443:443
            - 80:80
        networks:
            - proxy-services-net
        restart: unless-stopped

    crowdsec:
        image: docker.io/crowdsecurity/crowdsec:latest
        container_name: crowdsec
        security_opt:
            - no-new-privileges=true
        environment:
            - GID=${PGID}
            - COLLECTIONS=crowdsecurity/nginx crowdsecurity/http-cve crowdsecurity/whitelist-good-actors Dominic-Wagner/vaultwarden
            - CUSTOM_HOSTNAME=${HOSTNAME}
            #- LEVEL_DEBUG=true
        volumes:
            - ${PATH_SERVICES}/proxy-services/crowdsec/config:/etc/crowdsec:rw
            - ${PATH_SERVICES}/proxy-services/crowdsec/data:/var/lib/crowdsec/data:rw
            - ${PATH_SERVICES}/proxy-services/swag/log/nginx:/var/log/swag:ro
            - ${PATH_SERVICES}/vaultwarden/config/logs/vaultwarden.log:/var/log/vaultwarden.log:ro
            - /var/log:/var/log/host:ro      
        networks:
            - proxy-services-net
        restart: unless-stopped