networks:
    proxy-services-net: 
        name: proxy-services-net

services:
    swag:
        image: lscr.io/linuxserver/swag:latest
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - URL=${SWAG_URL}
            - SUBDOMAINS=wildcard
            - VALIDATION=dns
            - DNSPLUGIN=cloudflare
            - EMAIL=${SWAG_EMAIL}
            - MAXMINDDB_LICENSE_KEY=${MAXMINDDB_LICENSE_KEY}
            - DOCKER_MODS=ghcr.io/linuxserver/mods:swag-f2bdiscord
            - DISC_HOOK=${SWAG_DISC_HOOK}
            - DISC_ME=${DISC_ME}
            - DISC_API=${SWAG_DISC_API}
        volumes:
            - ${PATH_SERVICES}/proxy-services/swag:/config
            - ${PATH_SERVICES}/vaultwarden/config/logs/vaultwarden.log:/vaultwarden/vaultwarden.log:ro
            # TODO: Mount additional app logs here
        ports:
            - 443:443
            - 80:80
        networks:
            - proxy-services-net
        #depends_on:
        #    - authelia
        restart: unless-stopped

    # authelia:
    #     image: authelia/authelia:4.21.0
    #     container_name: authelia
    #     environment:
    #         - TZ=${TZ}
    #     volumes:
    #         - ${PATH_CONFIG}/authelia:/config
    #     restart: unless-stopped