services:
    photoprism:
        image: photoprism/photoprism:latest
        container_name: photoprism
        security_opt:
            - seccomp:unconfined
            - apparmor:unconfined
        environment:
            UID: ${PUID}
            GID: ${PGID}
            PHOTOPRISM_ADMIN_PASSWORD: ${ADMIN_PASSWORD}   # PLEASE CHANGE: Your initial admin password (min 4 characters)
            PHOTOPRISM_ORIGINALS_LIMIT: 1000               # File size limit for originals in MB (increase for high-res video)
            PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
            PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
            PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
            PHOTOPRISM_READONLY: "true"                    # Don't modify originals directory (reduced functionality)
            PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
            PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
            PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
            PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Disables using TensorFlow for image classification
            PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
            PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
            PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
            PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
            PHOTOPRISM_DATABASE_SERVER: "photoprism-db"    # MariaDB database server (hostname:port)
            PHOTOPRISM_DATABASE_NAME: ${MYSQL_DATABASE}    # MariaDB database schema name
            PHOTOPRISM_DATABASE_USER: ${MYSQL_USER}        # MariaDB database user name
            PHOTOPRISM_DATABASE_PASSWORD: ${MYSQL_PASSWORD} # MariaDB database user password
            PHOTOPRISM_SITE_URL: "http://localhost:8005/"  # Public PhotoPrism URL
            PHOTOPRISM_SITE_TITLE: "PhotoPrism"
            PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
            PHOTOPRISM_SITE_DESCRIPTION: ""
            PHOTOPRISM_SITE_AUTHOR: ""
        volumes:
            - ${PATH_PHOTO}:/photoprism/originals:ro
            - ./config:/photoprism/storage
        ports:
            - 8005:2342
        depends_on:
          - photoprism-db
        restart: unless-stopped

    photoprism-db:
        image: ghcr.io/linuxserver/mariadb:latest
        container_name: photoprism-db
        security_opt:
            - seccomp:unconfined
            - apparmor:unconfined
        command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./db:/config
        restart: unless-stopped