services:
    photoprism:
        image: photoprism/photoprism:latest
        container_name: photoprism
        security_opt:
            - seccomp:unconfined
            - apparmor:unconfined
        environment:
            PHOTOPRISM_ADMIN_PASSWORD: ${ADMIN_PASSWORD}   # PLEASE CHANGE: Your initial admin password (min 4 characters)
            PHOTOPRISM_SITE_URL: "http://localhost:8005/"  # Public server URL incl http:// or https:// and /path, :port is optional
            PHOTOPRISM_ORIGINALS_LIMIT: 5000               # File size limit for originals in MB (increase for high-res video)
            PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
            PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
            PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
            PHOTOPRISM_READONLY: "true"                   # Don't modify originals directory (reduced functionality)
            PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
            PHOTOPRISM_DISABLE_CHOWN: "false"              # Disables storage permission updates on startup
            PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
            PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
            PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Disables all features depending on TensorFlow
            PHOTOPRISM_DISABLE_FACES: "false"              # Disables facial recognition
            PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # Disables image classification
            PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
            PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
            PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
            PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
            PHOTOPRISM_DATABASE_SERVER: "photoprism-db"    # MariaDB or MySQL database server (hostname:port)
            PHOTOPRISM_DATABASE_NAME: ${MYSQL_DATABASE}    # MariaDB or MySQL database schema name
            PHOTOPRISM_DATABASE_USER: ${MYSQL_USER}        # MariaDB or MySQL database user name
            PHOTOPRISM_DATABASE_PASSWORD: ${MYSQL_PASSWORD} # MariaDB or MySQL database user password
            PHOTOPRISM_SITE_TITLE: "PhotoPrism"
            PHOTOPRISM_SITE_CAPTION: "BeastBox"
            PHOTOPRISM_SITE_DESCRIPTION: ""
            PHOTOPRISM_SITE_AUTHOR: ""
            ## Set a non-root user, group, or custom umask if your Docker environment doesn't support this natively:
            PHOTOPRISM_UID: ${PUID}
            PHOTOPRISM_GID: ${PGID}
            # PHOTOPRISM_UMASK: 0000
            ## Enable TensorFlow AVX2 support for modern Intel CPUs (requires starting the container as root):
            # PHOTOPRISM_INIT: "tensorflow-amd64-avx2"
            ## Hardware video transcoding config (optional):
            # PHOTOPRISM_FFMPEG_BUFFERS: "64"              # FFmpeg capture buffers (default: 32)
            # PHOTOPRISM_FFMPEG_BITRATE: "32"              # FFmpeg encoding bitrate limit in Mbit/s (default: 50)
            # PHOTOPRISM_FFMPEG_ENCODER: "h264_v4l2m2m"    # Use Video4Linux for AVC transcoding (default: libx264)
            # PHOTOPRISM_FFMPEG_ENCODER: "h264_qsv"        # Use Intel Quick Sync Video for AVC transcoding (default: libx264)
            # PHOTOPRISM_INIT: "intel-graphics tensorflow-amd64-avx2" # Enable TensorFlow AVX2 & Intel Graphics support
            HOME: "/photoprism"
            ## Hardware devices for video transcoding and machine learning (optional):
            # devices:
            #  - "/dev/video11:/dev/video11" # Video4Linux (h264_v4l2m2m)
            #  - "/dev/dri/renderD128:/dev/dri/renderD128" # Intel GPU
            #  - "/dev/dri/card0:/dev/dri/card0"
        working_dir: "/photoprism"
        volumes:
            - ${PATH_PHOTO}:/photoprism/originals:ro
            - ./config:/photoprism/storage
        ports:
            - 8005:2342
        depends_on:
            - photoprism-db
        restart: unless-stopped

    photoprism-db:
        image: lscr.io/linuxserver/mariadb:latest
        container_name: photoprism-db
        security_opt:
            - seccomp:unconfined
            - apparmor:unconfined
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./db:/config
        restart: unless-stopped