services:
    navidrome:
        image: deluan/navidrome:latest
        container_name: navidrome
        user: ${PUID}:${PGID}
        environment:
            # Optional: put your config options customization here. Examples:
            ND_SCANSCHEDULE: 1h
            ND_LOGLEVEL: info  
            ND_BASEURL: ""
        volumes:
            - ${PATH_SERVICES}/navidrome/config:/data
            - ${PATH_MEDIA}/music:/music:ro"
        ports:
            - 8003:4533
        restart: unless-stopped