services:
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        ports:
            - 8000:8000
            - 9000:9000
        volumes:
            - ./config:/data
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped