services:
    valheim-server:
        image: ghcr.io/lloesche/valheim-server:latest
        container_name: valheim-server
        cap_add:
            - sys_nice
        stop_grace_period: 2m
        env_file:
            - ${PATH_SERVICES}/valheim-server/valheim.env
        volumes:
            - ${PATH_SERVICES}/valheim-server/config:/config
            - ${PATH_SERVICES}/valheim-server/data:/opt/valheim
            - ${PATH_SERVICES}/valheim-server/backups:/backups
        ports: 
            - 2456-2457:2456-2457/udp
            - 9001:9001/tcp # Supervisor
            - 9002:9002/tcp # Status
        restart: unless-stopped