services:
    mealie-frontend:
      image: hkotel/mealie:frontend-v1.0.0beta-4
      container_name: mealie-frontend
      environment:
        - API_URL=http://mealie-api:9000
      ports:
        - 8006:3000
      volumes:
        - ${PATH_SERVICES}/mealie/config:/app/data
      restart: unless-stopped

    mealie-api:
      image: hkotel/mealie:api-v1.0.0beta-4
      container_name: mealie-api
      volumes:
        - ${PATH_SERVICES}/mealie/config:/app/data
      environment:
        - ALLOW_SIGNUP=true
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - MAX_WORKERS=1
        - WEB_CONCURRENCY=1
        #- BASE_URL=https://mealie.yourdomain.com
      restart: unless-stopped