# Action for building Flame container (experimental)
name: Build Flame

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create .env
        run: echo "${{ secrets.ENV_FLAME }}" > services/flame/.env
      - name: Build docker-compose.yml
        run: docker compose -f services/flame/docker-compose.yml build
