#Simple check if all containers can build and start
name: Build Containers

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and start containers
        run: find -name 'docker-compose.yml' -exec docker compose -f {} up -d \;

